version: '3.8'

services:
  webapp:
    image: kvsnikhil/web_app:2.0
    build: .
    ports:
      - "3001:3000"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s
